export const modifiers: { [key: string]: string } = {
    "BC": "Patches of",
    "BL": "Blowing",
    "BR": "Mist",
    "DR": "Low drifting",
    "DS": "Dust storm",
    "DU": "Dust",
    "DZ": "Drizzle",
    "FC": "Funnel cloud",
    "FG": "Fog",
    "FU": "Smoke",
    "FZ": "Freezing",
    "GR": "Hail",
    "GS": "Small hail and/or snow pellets",
    "HZ": "Haze",
    "IC": "Ice crystals",
    "MI": "Shallow",
    "PL": "Ice pellets",
    "PO": "Dust/sand whirls",
    "PR": "Partial",
    "PY": "Spray",
    "RA": "Rain",
    "SA": "Sand",
    "SG": "Snow grains",
    "SH": "Showers of",
    "SN": "Snow",
    "SP": "Snow pellets",
    "SQ": "Squall",
    "SS": "Sandstorm",
    "TS": "Thunderstorm",
    "UP": "Unknown precipitation",
    "VA": "Volcanic ash"
};